FROM openjdk:11-jre-slim-stretch

EXPOSE 8080

RUN mkdir /app

COPY build/libs/challengerbot-0.0.1-SNAPSHOT.jar /app/spring-boot-application.jar

ENTRYPOINT ["java", "-XX:+UnlockExperimentalVMOptions", "-Djava.security.egd=file:/dev/./urandom","-jar","/app/spring-boot-application.jar"]
